language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm install
- npm run lint
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: GiqDaju7YIs/DsYg1LrmiPszwBRudTmNCQAlbW7v834HLIn7otfYa8Gutiwc5V4RBbXZ2OOHdeETLJZuaaKO2tWG6DYMIQtxDwRqXBFnKeR1QBapgMyAFupE5DAMwi15dUZAkjKwkkCBIjG74ORq0VIb185NBWpfSy6X7JoiPCGmVXETtt3u5crPcES5bKFkWYbPeGUI1F/7I6tYEkqDmgq+yOd/vMfSLuiLW0JdtnYInsmzEiMvJ0zIq4Gwiq5PhcS++t48jOkEeaVJyzT/LxLcFHqBJ0CHVmx6HTGxg/rUuMiUJIHsM6eVSvgatEZApBHZlboyZx2E5DrTckYDOp1e+2azMp3YDR+9/g14moQwXqUa4WQSqD+soOzrQuCo+Rhve4ldDCKxGxubpwdUmt4J6nHy/ERM36XQHsWKK4W2xRbTPwPciJooYZj+E7oqWqs2bGm4o+9nPknEQOqlqN8eERbQblng12/k+3hNj48dCrBLvEb45urKHPn1DWzUiwHlnvB9GWQI4HAFv53M2CFoMRurQhu3X7x8c6WP3aOg7tbfmk7A5XOw5gZa+iKFXUo+Hcd8JVZ+cdh50u8/rZmhVzfZO+BlTjcgsKYak6pZDI+v91imuWgGr9fwoimrvcts0VK3OONm/9mKiLgtJC8hgqci8sLS4jGk5maPAuc=
  - secure: fybKt+rwPl9fyR0OHdLcYOAz+o9NZHUxarBAwoYtp54qnIvjBm90F9cd5U9QmNZ2iH4VEBfgSo9YIE+ith1PvGJV1mqdhz2JeWUP44g1ulladVtFcp+57xlP1/L8yH2zy0KxeyAK0Bm8CYYq4b8RkXKt/1uewtjNsCyBuyBzH7Bgc869h7/qoatGaPZxoZ3AndzV5ntmiHeU0d/1hOCwQr0in5wuhyAa75vS2RxFzgkFKum09LF1SAvtb9Mavw/HvYChI2JKmleheO+qeVSwTRXyd0Ccs61ngrRoKdgZG/jcC3DFk34Un3Fg7ZRhZj6OJa8tTVoR3c130JP5faMpUImSW3yUeqequUjNxDMtVJ7KVia94NLlOY0NPst39/vlnx0S4TlqwpFZk55vAKKeFvNWxAJ0Ll0P+Zycf5blD2VoWHLoLTDHLrWcDdXBc05l7mFggITkmcTsn33AnT3ntOgZ5QG0FXHuzAcCWj1hefvMIix/hjSa3fjkmSdkTDyYh6o8EUYBFunL6f7ONgigGhR4VP5+NjYGt9iybOoxJB0b16TaozU4sM9D+s/kTMYiIqsT2n1TUCXKEZt/LBTD3b8rG2SG+EUhOmY+YBlaMsaF/3darXzUgRscK8KgFzTwKSK7qUXDbV9lvw0wOsW5wjZJEvLIjjp6X6iQS3q8G4M=
  - secure: MnS0FDzSnvZjQaKSp/6Pc71Kzk8B7vj2dXOYLcfNBcVjkqLYV5/1NNZoyjhKtYICsO4p4F7RfeiosE5Aa7yySGeYZtzO9XrMAu86aybSiW94aNmvVEV0O2WtypxnA2S/YVnIrPGht91g3PflV9hh432KgJYssP4QiPPAqP51rqsSZD6VH6qNPTefv8fFOKDLSYyWyd76SlXM+2PHRHdAspZ8Dg/mW62mplCnA8egTJxGPYyTVdFLx8BlFuiTmAOwUcPULikyV7mTq4fDlzBLvP25AWUCIQ8AjsxFn1ILGCswkxhvzsrMEMQIh1bcMKuCLSyaHTJnYXFcpm0xE/RnCT3cNJVmSJNvvn4sfRGmvNw0VypB2uso8635AV3AWzvPQVL7ZyxhBe8dPdZ033s/+UCPy+Sh94m4xrMKq6goZ2XNYVEg56eomQoTxt4JeZPpYct0mpjwG6c3wT6RdDMSdL420jQyjF0n3paNnfoyYao9C8r3lVlx3i56FXHQAmmDS4eHBKRCpmJST8RQ63GSUkdRLj8NgI7KCyDw2Nz/ikTy0rR9iPyzHDxvHZYC4OsMn/Go123KaZaCIDgz/IfrI/Hk0c3dY8IbGw9+P6EPGrdAp5rTNu5uVdElmnlLmxrCGGGIU816/BxWV/9KqNrWdF6gUx/c+PoonYiupBy12ss=
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=callthemonline/simple-server-graphql
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f docker/Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker push $REPO
